### ISSUE TITLE
Update to latest FSharp.TypeProviders.StarterPack

### ISSUE THREAD

**Issue by CaringDev** [fsprojects/FSharp.Configuration#112]
[Tried](https://github.com/CaringDev/FSharp.Configuration/tree/StarterPack) to update to the latest version of [FSharp.TypeProviders.StarterPack](https://github.com/fsprojects/FSharp.TypeProviders.StarterPack) and got stuck with a non-working YamlProvider (NullReferenceException while generating the types for [Settings.yaml](https://github.com/fsprojects/FSharp.Configuration/blob/master/tests/FSharp.Configuration.Tests/Settings.yaml)) at [a commit of @dsyme](https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/commit/44e33a52935f78046f8da391043a952463c12e3c).

Haven't investigated yet... just wanted to record the commit hash here to prevent duplicate binary search effort.

**Comment by sergey-tihon** [comment]
@vasily-kirichenko Why this repo has custom ProvidedTypes.fs and how it differ?

**Comment by vasily-kirichenko** [comment]
@sergey-tihon no idea.
