### ISSUE TITLE
Package FSharp.Configuration 0.6.4 is not compatible with netcoreapp1.0

### ISSUE THREAD

**Issue by alvivar** [fsprojects/FSharp.Configuration#113]
Hi!

Are there any plans to make this library compatible with Netcore?

Full log:
> /usr/local/share/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error : Package FSharp.Configuration 0.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package FSharp.Configuration 0.6.4 supports: net40 (.NETFramework,Version=v4.0) [/Users/andresv/Projects/netcore-river/netcore-river.fsproj]
> /usr/local/share/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [/Users/andresv/Projects/netcore-river/netcore-river.fsproj]

**Comment by vasily-kirichenko** [comment]
No. A PR would be appreciated though.
