### ISSUE TITLE
Make inferring types from strings optional for Yaml provider

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/FSharp.Configuration#114]
Hi there! We started to have problems with the YamlConfig provider in our project because we've lists where some items look and quack like Guids, so the provider [infers the field type to be a Guid](https://github.com/fsprojects/FSharp.Configuration/blob/bc5ec3a8537a79f81ddc9f90eccdc37e383535ad/src/FSharp.Configuration/YamlConfigProvider.fs#L29-L33) list, but we want to be able to put other plain strings in that list and the provider doesn't let us do that as it fails when it tries to cast everything into a guid. This affects also TimeSpan and Uri-looking strings.

I'd like to send a PR to make inferring types from strings optional. I gave it a shot at adding another static parameter to YamlConfig and using a mutable value in Parser (to avoid too much refactoring) but unfortunately it didn't work, and this solution would also be breaking (besides not very elegant) as it seems it's not possible to have optional static parameters.

So before sending a PR, I want to ask the maintainers if they can think of a good approach to this problem.

**Comment by vasily-kirichenko** [comment]
Implemented in https://github.com/fsprojects/FSharp.Configuration/pull/115 and published in NuGet 1.0.0

![image](https://cloud.githubusercontent.com/assets/873919/24973169/84fda982-1fc6-11e7-8ca2-883859349a47.png)

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks!
