### ISSUE TITLE
Nuget package version 1.0 doesn't work with F# projects with a .NET version less than 4.6

### ISSUE THREAD

**Issue by a688** [fsprojects/FSharp.Configuration#116]
Using Visual Studio 2017, create a new F# console app targeting .NET 4.0
Add FSharp.Configuration (1.0.0) from nuget
go to your Program.fs file and at the top enter "open FSharp." <notice that configuration doesn't show up>
delete that line

Uninstall all nuget packages from the project
Update the project to target .NET 4.5.2
Add FSharp.Configuration (1.0.0) from nuget
go to your Program.fs file and at the top enter "open FSharp." <notice that configuration doesn't show up>
delete that line

Uninstall all nuget packages from the project
Update the project to target .NET 4.6
Add FSharp.Configuration (1.0.0) from nuget
go to your Program.fs file and at the top enter "open FSharp." 
the Configuration namespace finally shows up

**Comment by vasily-kirichenko** [comment]
Yes, it now targets .net 4.6.

**Comment by a688** [comment]
You are missing the point. 

Where on https://fsprojects.github.io/FSharp.Configuration/ does it say "Only works with .NET 4.6 or above".  It doesn't.

Where on https://github.com/fsprojects/FSharp.Configuration/blob/master/README.md does it say "Only works on .NET 4.6 or above".  It doesn't.

Version 0.6.4 WORKS with .NET 4.0 but version 1.0.0 doesn't. If newer version are no longer going to support .NET 4.0 then why not update the nuget package to limit the version to net46 instead of leaving it as net40?

**Comment by vasily-kirichenko** [comment]
Ah. I was not aware packages target .net versions. Please make a PR which either make it work on 4.0 or target 4.6
