### ISSUE TITLE
Provide a .NET Standard compatible build on nuget

### ISSUE THREAD

**Issue by pkese** [fsprojects/FSharp.Configuration#127]
This package is only available as for dotnet 4.5 and can't be used in modern .Net Core / .Net Standard enironments (Linux...).

Is there a reason it can't be provided as Netstandard compatible.

**Comment by vasily-kirichenko** [comment]
It's possible if SharpYaml package is Core compatible.

**Comment by pkese** [comment]
Yes,  
SharpYaml is compatible with NetStandard 1.6  
https://www.nuget.org/packages/SharpYaml/

**Comment by sergey-tihon** [comment]
How is it possible? I thought that TP does not work yet on .NET Core - https://github.com/Microsoft/visualfsharp/issues/2406

@vasily-kirichenko Do you know at least one (erased) TP that is compiled to .net standard and work on .net core?

**Comment by vasily-kirichenko** [comment]
Ah, I don't follow .NET Core news, I thought TPs are already supported.

**Comment by forki** [comment]
@vasily-kirichenko no they are not.

**Comment by tylerhartwig** [comment]
I noticed there are alpha releases for .netstandard on nuget. 

What is the state of those builds? How functional are they on netstandard?

**Comment by sergey-tihon** [comment]
@tylerhartwig plz, try it and tell us ;)

It is in alpha because it is does not contain `ResXProvider` at the moment and there is no way auto-magically load `web.config`.

`YamlConfigTypeProvider`, `IniFileProvider` & `AppSettingsTypeProvider` should be in perfect shape (as good as before).

**Comment by baronfel** [comment]
I had issues with the yamlprovider in Rider and vscode with regards to intellisense, but they compiled perfectly.

**Comment by sergey-tihon** [comment]
@baronfel what sorts of issues you had? Performance?
IIRC, current alpha does not contain `caching` for provided types. Can it be related?

**Comment by baronfel** [comment]
It was always just red squigglies for unknown members on the generated type. Just a design time issue, though! One of the many things I hadn't found time to run down.

**Comment by tylerhartwig** [comment]
Ah I'd love to try it out and let yall know, however I was hoping to try out the resx :D

Is that piece started? What does the work on that look like?

**Comment by sergey-tihon** [comment]
@tylerhartwig yes, take a look here https://github.com/fsprojects/FSharp.Configuration/pull/139#issuecomment-448216452

the original implementation is heavily rely on winforms that is not net-standard thing =(

**Comment by sergey-tihon** [comment]
We also can ask @Liminiens opinion on how far we are ;)

**Comment by Liminiens** [comment]
@sergey-tihon i beleive it is be possible to target net core 3.0 for resx provider since it has win forms bits, but it needs some research

**Comment by sergey-tihon** [comment]
@Liminiens maybe, but it anyway will be win-only. right?

**Comment by Liminiens** [comment]
yes :)

**Comment by jkone27** [comment]
any news on .netstandard porting effort ? maybe YAML type provider should be in the main FSharp.Data library?

**Comment by sergey-tihon** [comment]
@jkone27 have you tried [2.0.0-alpha2](https://www.nuget.org/packages/FSharp.Configuration/2.0.0-alpha2)? It contains .net standard version of YAML type provider

**Comment by jkone27** [comment]
Will give it a try, thanks a lot @sergey-tihon  👍

**Comment by jkone27** [comment]
just a thought, but any thoughts of migrating it to FSharp.Data ?  i think it could prove very useful and maybe it's a nicer fit there, or have a separate package/repo like FSharp.Data.Yaml ?  Have a really nice day!
