### ISSUE TITLE
.Net core compatability?

### ISSUE THREAD

**Issue by Whil-** [fsprojects/FSharp.Configuration#160]
Hi,

Tried this with a .Net Core 3.1 app but got issues hinting at no support for core just yet. Is .Net Core 3.1 supported or not?

And if not, then please either add it or make a note that this is .Net Framework specific in the readme.

Thanks

**Comment by sergey-tihon** [comment]
what version have you tried? (latest alpha?)

**Comment by Whil-** [comment]
Tried 1.5

**Comment by bethmaloney** [comment]
@Whil- I've been using [2.0.0 Alpha 2](https://www.nuget.org/packages/FSharp.Configuration/2.0.0-alpha2) with .net core 3.1 with no issues. I have to add System.Configuration.ConfigurationManager otherwise I get a runtime error when trying to access a value from the config file.

**Comment by Whil-** [comment]
Ok, thanks for the information. Glad to see it's in progress.
