### ISSUE TITLE
YamlConfig intellisense fails on Visual Studio 16.10.0 and above

### ISSUE THREAD

**Issue by sircuri** [fsprojects/FSharp.Configuration#162]
The moment we upgraded to Visual Studio 16.10.0 we get intellisense issues on dependent projects that use the YamlConfig type provider.

I have created a public repository with a minimal Visual Studio solution that shows the error: 
https://github.com/sircuri/yamltypeprovider

If you open this solution in Visual Studio 16.9.10 or below, no intellisense errors are shown in the file `Boundaries.fs`. If you open the solution in Visual Studio 16.10.0 and above, the F# file complains about missing the Framework-namespace.

Visual Studio 16.9.10 <
![image](https://user-images.githubusercontent.com/1629284/133283685-c77e5a80-8273-42f5-b120-1e3cc0aa7efe.png)

Visual Studio 16.10.0 >
![image](https://user-images.githubusercontent.com/1629284/133283574-8c7b49d8-b919-4122-aa16-ffa7b45953d8.png)
If you now remove the YamlConfig declaration from Daemon.fs, the error goes away.

The compiler does not show any errors on either versions of Visual Studio.

The IniFile provider does work correctly on both Visual Studio versions. Only the YamlConfig type seems to be affected.
I hope you are able to help with this.

**Comment by sergey-tihon** [comment]
It is very strange. Have you tried restart IDE? =)
Just tried in VS 16.11.3 and it works 

<img width="949" alt="image" src="https://user-images.githubusercontent.com/1197905/133409502-3f5fbc2d-61ec-4b79-8d30-659be0041b0a.png">

**Comment by sircuri** [comment]
Can you please open the Boundaries.fs file from the other project. That is the one that is failing.

**Comment by sergey-tihon** [comment]
Ah, I see! It really looks like IDE regression https://github.com/dotnet/fsharp/issues/12078 & https://github.com/dotnet/fsharp/issues/12082

**Comment by sircuri** [comment]
Thank you very much. I tried to find answers and solutions to this problem but could not find any. Thanks for pointing to those other issues. It indeed looks like the same issue I'm facing.
I do wonder why the INI type provider does not appear to be affected.

**Comment by sergey-tihon** [comment]
Interesting, but it works in VS2022 Preview 4
so you can use cutting edge IDE )))

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/1197905/133429506-acef8a7c-7f26-4402-ba28-d6e39f3ad2a8.png">
