### ISSUE TITLE
Unable to install FSharp.Configuration NuGet package into an F# project, works OK with C#

### ISSUE THREAD

**Issue by object** [fsprojects/FSharp.Configuration#56]
If I create a new F# library project using VS 2013 and try to install FSharp.Configuration NuGet package, I am getting the following error:

PM> install-package FSharp.Configuration
Installing 'FSharp.Configuration 0.5.0'.
Successfully installed 'FSharp.Configuration 0.5.0'.
Adding 'FSharp.Configuration 0.5.0' to Library1.
No exact match found for removing reference 'SharpYaml'. Trying case-insensitive search...
Failed to find match for removing reference 'SharpYaml'.
Uninstalling 'FSharp.Configuration 0.5.0'.
Successfully uninstalled 'FSharp.Configuration 0.5.0'.
Install failed. Rolling back...
install-package : Failed to add reference to 'SharpYaml'.
At line:1 char:1
- install-package FSharp.Configuration
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

If I create an empty C# library project, then everything works fine.

**Comment by vasily-kirichenko** [comment]
Cannot reproduce it. 

On a blank F# console app:

```
PM> Install-Package FSharp.Configuration
Installing 'FSharp.Configuration 0.5.1'.
Successfully installed 'FSharp.Configuration 0.5.1'.
Adding 'FSharp.Configuration 0.5.1' to FSharp.Configuration.Sandbox.
Successfully added 'FSharp.Configuration 0.5.1' to FSharp.Configuration.Sandbox.
```

On a F# library:

```
PM> Install-Package FSharp.Configuration
'FSharp.Configuration 0.5.1' already installed.
Adding 'FSharp.Configuration 0.5.1' to Lib.
Successfully added 'FSharp.Configuration 0.5.1' to Lib.
```

**Comment by viking84red** [comment]
I have the same issue
