### ISSUE TITLE
Problem with floating point scalars

### ISSUE THREAD

**Issue by Turee** [fsprojects/FSharp.Configuration#57]
When i try to define floating point numbers in yaml files type provider reports following error:
'FSharp.Configuration.ConfigTypeProvider+FSharpConfigurationProvider' reported an error: Input string was not in a correct format.	

Example yaml file (issue reproduces):
```yaml
Test:
    AFloatingPointNumber: 0.1
```

This works fine:
```yaml
Test:
    AIntegerNumber: 1
```

**Comment by vasily-kirichenko** [comment]
Try `0,1`.

**Comment by Turee** [comment]
That seems to work. I browsed the type provider code and i thought the parsing is culture invariant. Shouldn't this be the case?

**Comment by vasily-kirichenko** [comment]
What do you suggest to fix it? It should be able to parse floats with any decimal separator on machines with any culture.

**Comment by Turee** [comment]
I do not have a fix yet but i can look into it. Just wanted to make sure this is not a known issue.

**Comment by Turee** [comment]
The issue was with the SharpYaml failing to parse the 0.1 formatted double value. => Updated SharpYaml that now works. Second issue was with calling a double values ToString() method, which is not culture invariant. Then parser parsed the double with culture invariant setting on resulting invalid results.

**Comment by Turee** [comment]
I'm creating a pull request.
