### ISSUE TITLE
Better exception/error mesages

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Configuration#65]
If expected connection string entry is missing at run-time the type provider throws 

System.NullReferenceException: Object reference not set to an instance of an object.
   at FSharp.Configuration.AppSettingsTypeProvider.getConnectionString(String key) in 
D:\git\FSharp.Configuration\src\FSharp.Configuration\AppSettingsProvider.fs:line 28

It would be nice if it can raise more meaningful error. Something like
raise <| System.KeyNotFoundException(sprintf "Cannot find name %s in <connectionStrings> section of config file." "AdventureWork") 

I do similar thing in FSharp.Data.SqlClient
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/Configuration.fs#L88

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/FSharp.Configuration/commit/8b97fb9d776c76a1293cd4cd4b63d6e6b73da8f6
