### ISSUE TITLE
Yaml LoadAndWatch and Parse Errors.

### ISSUE THREAD

**Issue by sillyotter** [fsprojects/FSharp.Configuration#70]
When I call Yaml.Load on an unparseable yaml file, I get an exception that I can catch and handle.  That's perfect.  When I call Yaml.LoadAndWatch and I then change the file to something unparseable, the exception that is generated is thrown in some background thread created by the filesystemwatcher and is not something I can catch (short of an unhandledthreadexception handler).  

I initially looked at the code to see if I could modify things so that the Changed events would return a disc union of Success|Error(exn) but found that was an awfully complicated change.

I don't like the idea of eating the parse exception in LoadAndWatch, but I might be able to argue that an unparseable change isn't a change in the sense the method implies.  Id prefer to find a way to get the Changed event handler to let me know that it failed, but I'm not even sure that's possible from what I was reading.  Would consuming the exception in the watcher callback be appropriate?

Does anyone else have any better ideas on how to deal with parse exceptions in the LoadAndWatch callbacks?

**Comment by vasily-kirichenko** [comment]
I think a dedicated event would work well for this, like `MailboxProcessor.Error` one. What do you think? If you agree, it's easy to make a PR.

**Comment by sillyotter** [comment]
So, grab the exceptions in the watcher callback, and instead of re-raising it, push it on to the event  [here](https://github.com/fsprojects/FSharp.Configuration/blob/master/src/FSharp.Configuration/YamlConfigProvider.fs#L384)?  That seems like that would work.  Would we also push the parse errors on the event channel in the standard load call?  I assume not, but if I saw this for the first time I'd probably expect the error channel to be used all the time.  Or else, find a way to make it obvious the error channel was only there for the LoadAndWatch.  Somehow return it from the call?

**Comment by vasily-kirichenko** [comment]
Yes, I think that triggering the error even in case of exception during normal `Load` is a good idea, but maybe it should be done in a separate thread (`async { errorEvent.Trigger e } |> Async.Start`), and we should keep current `rerase` untouched.

**Comment by CumpsD** [comment]
Just experienced this too with the `LoadAndWatch`. Would be nice to catch this nicely.

**Comment by sillyotter** [comment]
It only took two months, but I finally found time to make the fix we discussed above.  Seems to work as needed.  But let me know if it needs more work.

**Comment by sillyotter** [comment]
OK, this one is correct.  I missed a CLIEvent tag on my event which caused things to happen I hadn't expected and couldn't originally believe were errors that I could have caused.  All unit tests pass on both windows and linux/mono.  Sorry for the earlier problems.
