### ISSUE TITLE
TypeInitializationException at runtime

### ISSUE THREAD

**Issue by matteo-mosca** [fsprojects/FSharp.Configuration#72]
I added the library via nuget. I followed the example, and at design time I get the intellisense for the <key> tags I put in my app.config file inside the <appSettings> node.

When I try to run the program, I get a generic TypeInitializationException with no details. Commenting out the type provider solves the problem.

I am using F# runtime 4.4 with .Net 4.5.2 in VS2015. The project type is a normal F# Console Application.

**Comment by sergey-tihon** [comment]
What TypeProvider have you tried?

**Comment by matteo-mosca** [comment]
The AppSettings provider, sorry for the missing info.

I also tried doing the same thing on a different machine, same configuration, and I got a different behaviour, but still wrong. Now at design time I see:

- A non existing connectionstring named "LocalSqlServer" (I don't even have a connectionstrings node in my app.config)
- My appSettings keys as I defined them

At runtime I get:

- That connection string, containing a default .\sqlexpress connectionstring with an attached mdf
- When trying to access any key of the appSettings node I get a 'System.Collections.Generic.KeyNotFoundException' 
- The ConfigFileName returns the correct app.config, the one in my application project path

**Comment by ochkin** [comment]
I am having the same "TypeInitializationException" when using AppSettings provider:
I have a WebAPI C# application that is referencing F# library (F# 4.0, FSharp.Core 4.4, .NET 4.6.1).
The latest version of Nuget package FSharp.Configuration 0.5.12.

**Comment by vasily-kirichenko** [comment]
1. **Always** use FSharp.Core NuGet package to reference FSharp.Core.dll instead of the one from GAC (for F# projects you have to make one more step: open the project file in an editor and remove GAC's FSharp.Core reference by hand).
2. **Always** add binding redirect for FSharp.Core into your app.config (if you use Paket, it does it automatically).

**Comment by ochkin** [comment]
Thanks, Vasily!
The innerException said that it attempted to load FSharp.Core 4.3 even though I didn't reference it anywhere.
Adding a binding redirect solved the problem.

**Comment by chinwobble** [comment]
@vasily-kirichenko  
I tried both workarounds you suggested and I sitll get the TypeInitializationException exception wit hthe below error.

Additional information: The type initializer for '<StartupCode$AssystScriptingUtilities-Common>.$Utils.Common.Configuration' threw an exception.

I'm trying to reference a configuration element from c#. 
My settings looks like this:
```
module Utils.Common.Configuration

open FSharp.Configuration

type Settings = AppSettings<"App.config">
let assystRESTServer = Settings.AssystAPIServer
```

I'm trying to get the config values in c# using the following:
```
var val = Utils.Common.Configuration.AssystRESTCredentials;
```
