### ISSUE TITLE
Working with new AspNetCore project.josn & hosting.json

### ISSUE THREAD

**Issue by WilliamBerryiii** [fsprojects/FSharp.Configuration#94]
I wanted to start a discussion to see about interest in extending the library to cover AspNetCore's project.json and hosting.json configuration files.  Though the AspNet team seems to still be shaking the kinks out of what goes where, having these configs pre-baked into the library would ease the ultimate transition to AspNetCore.

**Comment by WilliamBerryiii** [comment]
This should likely be closed in light of today's AspNet stand-up.

**Comment by vasily-kirichenko** [comment]
:)
