### ISSUE TITLE
Required documentation for using yaml typeprovider to set up the SQLProvider in production

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/FSharp.Configuration#99]
### Description

Required documentation for using yaml typeprovider to set up the SQLProvider in production.

### Repro steps

1 Create Config.yaml file like this:

```yaml
DB:
    ConnectionString: Data Source=....
```
2 Set up the Yaml Type Provider

```fsharp
type Config = YamlConfig<".\config.yaml"> 
let config = Config ()
let connectionString = config.DB.ConnectionString
```

3 Set up Sql Provider and use the ConnectionString 

```fsharp
let [<Literal>] CompileTimeConnectionString = "Data Source=..."
type Sql = SqlDataProvider<ConnectionString = CompileTimeConnectionString, UseOptionTypes=true>
let db = Sql.GetDataContext connectionString
```

### Expected behavior

The Yaml typeprovider should provide the connection string for the Sqlprovider which is then connecting to the db.

### Actual behavior

The Yaml typeprovider provides the connection string for the Sqlprovider which is then connecting to the db.

### Known workarounds

None known

### Related information 

* Operating system: Win 7
* Database versions: SQL Server 2008
* using Visual Studio 2015

**Comment by vasily-kirichenko** [comment]
I'm not sure I understand what you'd like to have here. And please, do not use the issue template, I don't find it any useful, it just adds noise.

**Comment by forki** [comment]
This is a reminder. Tim wants to write a tutorial on how to use
yamlprovider together with SQLProvider.

**Comment by forki** [comment]
But I think it should go to SQLProvider

**Comment by tforkmann** [comment]
ok sorry. closing it now.
